# Generated by Django 6.0 on 2026-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourPosition', models.PositiveIntegerField()),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'ordering': ['tourPosition'],
            },
        ),
    ]
