# Generated by Django 6.0 on 2026-01-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledStopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('direction', models.CharField(choices=[('to_city', 'To City'), ('from_city', 'From City')], max_length=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buschecker.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buschecker.busstop')),
            ],
            options={
                'ordering': ['arrival_time'],
            },
        ),
    ]
