# Generated by Django 6.0 on 2026-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buschecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledstoptimes',
            name='arrival_time',
            field=models.TimeField(),
        ),
    ]
